#! /bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin

# LSB functions aren't available, fake them
log_daemon_msg() { printf "%s: %s" "$1" "$2"; }
log_end_msg() { [ "$1" -eq 0 ] && echo " OK" || echo " FAIL"; }

DESC="Run a set of applications as daemons."
NAME=supervisord
DAEMON=/usr/sbin/$NAME
SUPERVISORCTL=/usr/sbin/supervisorctl
PIDFILE=/var/run/$NAME.pid
DAEMON_ARGS=" -c /etc/supervisord.conf --pidfile ${PIDFILE}"
SCRIPTNAME=/etc/init.d/$NAME

[ -x "$DAEMON" ] || exit 0

start() {
	[ -e $PIDFILE ] && return 1

	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
		$DAEMON_ARGS ||
		return 2
}

stop() {
	[ -e $PIDFILE ] || return 1

	# Stop all processes under supervisord control.
	$SUPERVISORCTL stop all

	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2
	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
	[ "$?" = 2 ] && return 2
	rm -f $PIDFILE
	return "$RETVAL"
}

case "$1" in
start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	start
	case "$?" in
	0 | 1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
	2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	stop
	case "$?" in
	0 | 1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
	2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
restart | force-reload)
	log_daemon_msg "Restarting $DESC" "$NAME"
	stop
	case "$?" in
	0 | 1)
		start
		case "$?" in
		0) log_end_msg 0 ;;
		1) log_end_msg 1 ;; # Old process is still running
		*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	*)
		# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
*)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

:
